kind: ConfigMap
apiVersion: v1
metadata:
  name: binderhub-template-gesis
  labels:
    app: binder
    component: etc-binderhub
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- (.Files.Glob "files/etc/binderhub/gesis/templates/*").AsConfig | nindent 2 }}
