apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kube-lego
  labels:
    app: kube-lego
    release: {{ .Release.Name }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: kube-lego
      release: {{ .Release.Name }}
