apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: cert-manager
  labels:
    app: cert-manager
    release: {{ .Release.Name }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: cert-manager
      release: {{ .Release.Name }}
