# dependabot.yaml reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# Notes:
# - Status and logs from dependabot are provided at
#   https://github.com/jupyterhub/mybinder.org-deploy/network/updates.
# - YAML anchors are not supported here or in GitHub Workflows.
#
version: 2

updates:
  # Maintain Python dependencies for building documentation
  - package-ecosystem: pip
    directory: /docs
    allow:
      - dependency-type: all
    groups:
      docs:
        patterns:
          - "*"
    schedule:
      interval: monthly
    labels:
      - dependencies

  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    labels: [ci]
    schedule:
      interval: monthly

  # Python dependencies in our deployment environment (pip-compile)
  - package-ecosystem: pip
    directory: "/"
    allow:
      # need 'all' here to update everything in requirements.txt
      # because the default 'direct' only updates what's in requirements.in
      - dependency-type: all
    schedule:
      interval: weekly
    labels:
      - dependencies

  # repeat for each image
  - package-ecosystem: pip
    directory: "/images/analytics-publisher"
    allow:
      - dependency-type: all
    groups:
      analytics-publisher:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: "/images/federation-redirect"
    allow:
      - dependency-type: all
    groups:
      federation-redirect:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: "/images/minesweeper"
    allow:
      - dependency-type: all
    groups:
      minesweeper:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: "/images/minesweeper"
    allow:
      - dependency-type: all
    groups:
      minesweeper:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: "/images/minesweeper"
    allow:
      - dependency-type: all
    groups:
      minesweeper:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: "/images/pod-cleaner"
    allow:
      - dependency-type: all
    groups:
      pod-cleaner:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - dependencies
