variables:
  GIT_STRATEGY: clone
  GIT_CLEAN_FLAGS: "-ffdx"
  # Change pip's cache directory to be inside the project directory since we can only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  EXTRA_VALUES_ACCEPTANCE: '--values ./secrets/config/common/common.yaml --values ./secrets/config/common/cryptnono.yaml --values ./secrets/config/common/gesis.yaml --values ./secrets/config/gesis-acceptance.yaml --values ./config/gesis.yml --values ./config/gesis-acceptance.yml'

# This workflow:rules are required to enable merge request pipelines!
workflow:
  rules:
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - lint
  - deploy-acceptance-helm
  - test-acceptance
  - deploy-production-helm
  - test-production

build helm chart:
  stage: build
  rules:
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  # Python version blocked by https://github.com/jupyterhub/mybinder.org-deploy/issues/3168
  image: python:3.11.11-bookworm
  cache:
    paths:
      - .cache/pip
  script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade setuptools pip
    - pip install --upgrade -r requirements.txt
    - |
      chartpress \
      --no-build
  artifacts:
    expire_in: 1h
    paths:
      - mybinder-kube-system/Chart.yaml
      - mybinder-tigera-operator/Chart.yaml
      - mybinder/Chart.yaml
      - mybinder/values.yaml

include:
  - component: $CI_SERVER_FQDN/rse/docker/images/helm/helm-lint@1.1.5
    inputs:
      stage: lint
      dir: mybinder
      extra_values: ${EXTRA_VALUES_ACCEPTANCE}
      git_crypt: 'true'
    rules:
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == 'merge_request_event'
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

  - component: $CI_SERVER_FQDN/rse/docker/images/helm/helm-deploy@1.1.5
    inputs:
      stage: deploy-acceptance-helm
      environment: acceptance
      dir: mybinder
      k8s_context: methods-hub/binder.methodshub.gesis.org:acceptance
      extra_values: ${EXTRA_VALUES_ACCEPTANCE}
      git_crypt: 'true'
    rules:
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == 'merge_request_event'
