[workspace]
authors = ["Project Jupyter Contributors <jupyter@googlegroups.com>"]
channels = ["conda-forge"]
name = "interactive-environment"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
