{{- if .Values.registry.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  labels:
    app: registry
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/tls-acme: "true"
    # This has to accomodate the max size of a single docker layer, which can be huge.
    # I had previously set this to 4G thinking 'that should be big enough' and was
    # immediately proven wrong. This is set to 16G now
    nginx.ingress.kubernetes.io/proxy-body-size: 16384m
spec:
  ingressClassName: nginx
  rules:
    {{- range $host := .Values.registry.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 5000
    {{- end }}
  tls:
    - secretName: tls-registry
      hosts:
        {{- range $host := .Values.registry.ingress.hosts }}
        - {{ $host }}
        {{- end }}
{{- end }}
