{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    app: registry
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  auth.htpasswd: {{ htpasswd .Values.registry.auth.username .Values.registry.auth.password | b64enc }}
{{- end }}
