{
 "title": "1. Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Federation health",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "max(federation_health) by (member)",
     "legendFormat": "{{ member }}"
    },
    {
     "expr": "max(federation_health_check) by (member, check)",
     "legendFormat": "{{ member }} {{ check }}"
    }
   ]
  },
  {
   "title": "Builds over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"build-.*\", pod!~\"build-cache-prune-.*\", kubernetes_namespace!=\"jhub-ns\"})",
     "legendFormat": "GESIS"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"build-.*\", pod!~\"build-cache-prune-.*\", kubernetes_namespace!=\"jhub-ns\"})",
     "legendFormat": "2i2c"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"build-.*\", pod!~\"build-cache-prune-.*\", kubernetes_namespace!=\"jhub-ns\"})",
     "legendFormat": "BIDS"
    }
   ]
  },
  {
   "title": "Launches over time",
   "type": "timeseries",
   "description": "Total new launches (10m)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(binderhub_launch_time_seconds_count[10m]))",
     "legendFormat": "GESIS"
    },
    {
     "expr": "sum(increase(binderhub_launch_time_seconds_count[10m]))",
     "legendFormat": "2i2c"
    },
    {
     "expr": "sum(increase(binderhub_launch_time_seconds_count[10m]))",
     "legendFormat": "BIDS"
    }
   ]
  },
  {
   "title": "User pods running over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^jupyter-.*\", phase=\"Running\"})",
     "legendFormat": "GESIS"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^jupyter-.*\", phase=\"Running\"})",
     "legendFormat": "2i2c"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^jupyter-.*\", phase=\"Running\"})",
     "legendFormat": "BIDS"
    }
   ]
  },
  {
   "title": "Requests waiting build",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(binderhub_inprogress_builds)",
     "legendFormat": "GESIS"
    },
    {
     "expr": "sum(binderhub_inprogress_builds)",
     "legendFormat": "2i2c"
    },
    {
     "expr": "sum(binderhub_inprogress_builds)",
     "legendFormat": "BIDS"
    }
   ]
  },
  {
   "title": "Requests waiting launch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum(binderhub_inprogress_launches)",
     "legendFormat": "GESIS"
    },
    {
     "expr": "sum(binderhub_inprogress_launches)",
     "legendFormat": "2i2c"
    },
    {
     "expr": "sum(binderhub_inprogress_launches)",
     "legendFormat": "BIDS"
    }
   ]
  },
  {
   "title": "Distribution of user pod age over time (max 2 hr)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "(time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of user pod age over time (stale pods)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "(time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60",
     "legendFormat": "GESIS"
    },
    {
     "expr": "(time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60",
     "legendFormat": "2i2c"
    },
    {
     "expr": "(time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of build pod age over time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "(time() - kube_pod_created{pod=~\"^build-.*\", pod!~\"build-cache-prune-.*\"}) / 60"
    },
    {
     "expr": "(time() - kube_pod_created{pod=~\"^build-.*\", pod!~\"build-cache-prune-.*\"}) / 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() - kube_pod_created{pod=~\"^build-.*\", pod!~\"build-cache-prune-.*\"}) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Launch/Build Success % [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(binderhub_build_time_seconds_count{status=\"success\", kubernetes_namespace!=\"jhub-ns\"}[10m])) / sum(increase(binderhub_build_time_seconds_count{kubernetes_namespace!=\"jhub-ns\"}[10m]))",
     "legendFormat": "Build % Success"
    },
    {
     "expr": "sum(increase(binderhub_launch_time_seconds_count{status=\"success\", kubernetes_namespace!=\"jhub-ns\"}[10m])) / sum(increase(binderhub_launch_time_seconds_count{status!=\"retry\", kubernetes_namespace!=\"jhub-ns\"}[10m]))",
     "legendFormat": "Launch % Success"
    },
    {
     "expr": "sum(increase(binderhub_launch_time_seconds_count{status=\"success\", retries=\"0\", kubernetes_namespace!=\"jhub-ns\"}[10m])) / sum(increase(binderhub_launch_time_seconds_count{status!=\"retry\", kubernetes_namespace!=\"jhub-ns\"}[10m]))",
     "legendFormat": "Launch % Success (first try)"
    },
    {
     "expr": "sum by (status) (increase(binderhub_launch_count_total{status!=\"success\"}[10m])) / ignoring (status) group_left sum(increase(binderhub_launch_count_total[10m])) ",
     "legendFormat": "{{ status }} rejection %"
    }
   ]
  },
  {
   "title": "Build time percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(binderhub_build_time_seconds_bucket[2m])) without (instance, provider, repo)) > 0",
     "legendFormat": "50th-percentile-{{status}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(binderhub_build_time_seconds_bucket[2m])) without (instance, provider, repo)) > 0",
     "legendFormat": "90th-percentile-{{status}}"
    }
   ]
  },
  {
   "title": "Launch time percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(binderhub_launch_time_seconds_bucket[5m])) without (retries, kubernetes_node, instance, repo, provider)) > 0",
     "legendFormat": "50th-percentile-{{status}} "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(binderhub_launch_time_seconds_bucket[5m])) without (instance, kubernetes_node, repo, provider)) > 0",
     "legendFormat": "90th-percentile-{{status}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(binderhub_launch_time_seconds_bucket[5m])) without (instance, kubernetes_node, repo, provider)) > 0",
     "legendFormat": "99th-percentile-{{status}}"
    }
   ]
  }
 ]
}