{
 "title": "Harbor",
 "description": "Overview Dashboard for the open-source Harbor Image Repository",
 "tags": [ "harbor" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Harbor instance",
    "query": {
     "query": "label_values(harbor_system_info,instance)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(harbor_project_artifact_total{instance=~\"$instance\"},project_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Harbor instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(harbor_system_info{instance=~\"$instance\", job=\"harbor-exporter\"}, \"instance\", \"$1\", \"instance\", \"(.*):9090\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Harbor version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_system_info{instance=~\"$instance\",job=\"harbor-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Self registration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_system_info{instance=~\"$instance\",job=\"harbor-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_system_info{instance=~\"$instance\",job=\"harbor-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_health{instance=~\"$instance\",job=\"harbor-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Component status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Component status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{instance=~\"$instance\",job=\"harbor-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Projects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total projects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (harbor_project_total{instance=~\"$instance\",job=\"harbor-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New projects last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(harbor_project_total{instance=~\"$instance\", job=\"harbor-exporter\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project type",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (harbor_project_total{instance=~\"$instance\",job=\"harbor-exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (public)(harbor_project_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (harbor_project_quota_usage_byte{instance=~\"$instance\",job=\"harbor-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories by project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_name)(harbor_project_repo_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota usage by project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_name) (harbor_project_quota_usage_byte{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members by project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(project_name) (harbor_project_member_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artifacts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total artifacts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(harbor_project_artifact_total{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Artifacts by Project",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(project_name) (harbor_project_artifact_total{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Artifacts by project",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by (project_name)(harbor_project_artifact_total{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Artifacts pulled by project",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(project_name) (harbor_artifact_pulled{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Artifacts pulled by project",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by(project_name) (harbor_artifact_pulled{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}