{
 "title": "Memory usage",
 "description": "Watch memory usage of pods and nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Load5 per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5 * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory consumption user nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"prod\", instance=~\"gke-prod-a-user.*\"}) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Top 5 user pods memory consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{pod_name=~\"jupyter-.*\"}) by (pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Requested memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes and on (pod) (kube_pod_container_status_ready)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory consumption core nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"prod\", instance=~\"gke-prod-a-core.*\"}) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  }
 ]
}