{
 "title": "Cluster Information",
 "tags": [
  "jupyterhub",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Running Users",
   "type": "graph",
   "description": "Count of running users, grouped by namespace\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{phase=\"Running\"}\n  * on (namespace, pod) group_right() kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\" }\n) by (namespace)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory commitment %",
   "type": "graph",
   "description": "% of total memory in the cluster currently requested by to non-placeholder pods.\n\nIf autoscaling is efficient, this should be a fairly constant, high number (>70%).\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (\n    # Get individual container memory requests\n    kube_pod_container_resource_requests{resource=\"memory\"}\n    # Add node pool name as label\n    * on(node) group_left(label_cloud_google_com_gke_nodepool) kube_node_labels{}\n  )\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (label_cloud_google_com_gke_nodepool)\n/\nsum(\n  # Total allocatable memory on a node\n  kube_node_status_allocatable{resource=\"memory\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_cloud_google_com_gke_nodepool) kube_node_labels{}\n) by (label_cloud_google_com_gke_nodepool)\n",
     "legendFormat": "{{label_cloud_google_com_gke_nodepool}}"
    }
   ]
  },
  {
   "title": "CPU commitment %",
   "type": "graph",
   "description": "% of total CPU in the cluster currently requested by to non-placeholder pods.\n\nJupyterHub users mostly are capped by memory, so this is not super useful.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (\n    # Get individual container memory requests\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    # Add node pool name as label\n    * on(node) group_left(label_cloud_google_com_gke_nodepool) kube_node_labels{}\n  )\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (label_cloud_google_com_gke_nodepool)\n/\nsum(\n  # Total allocatable memory on a node\n  kube_node_status_allocatable{resource=\"cpu\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_cloud_google_com_gke_nodepool) kube_node_labels{}\n) by (label_cloud_google_com_gke_nodepool)\n",
     "legendFormat": "{{label_cloud_google_com_gke_nodepool}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_labels) by (label_cloud_google_com_gke_nodepool)",
     "legendFormat": "{{label_cloud_google_com_gke_nodepool}}"
    }
   ]
  },
  {
   "title": "Non Running Pods",
   "type": "graph",
   "description": "Pods in states other than 'Running'.\n\nIn a functional clusters, pods should not be in non-Running states for long.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 } },
  {
   "title": "Node CPU Utilization %",
   "type": "graph",
   "description": "% of available CPUs currently in use\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (node)\n/\nsum(kube_node_status_capacity{resource=\"cpu\"}) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization %",
   "type": "graph",
   "description": "% of available Memory currently in use\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (\n  sum (\n    # Memory that can be allocated to processes when they need\n    node_memory_MemFree_bytes + # Unused bytes\n    node_memory_Cached_bytes + # Shared memory + temporary disk cache\n    node_memory_Buffers_bytes # Very temporary buffer memory cache for disk i/o\n  ) by (node)\n  /\n  sum(node_memory_MemTotal_bytes) by (node)\n)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node CPU Commit %",
   "type": "graph",
   "description": "% of each node guaranteed to pods on it\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory limits\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (node)\n/\nsum(\n  # Get individual container memory requests\n  kube_node_status_allocatable{resource=\"cpu\"}\n) by (node)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Commit %",
   "type": "graph",
   "description": "% of each node guaranteed to pods on it\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory limits\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (node)\n/\nsum(\n  # Get individual container memory requests\n  kube_node_status_allocatable{resource=\"memory\"}\n) by (node)\n",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}