{
 "title": "status",
 "description": "A dashboard to hold plots for status.mybinder.org",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests waiting on launches/builds",
   "type": "timeseries",
   "description": "The number of outstanding requests waiting on a pending build or launch",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(binderhub_inprogress_builds)",
     "legendFormat": "builds"
    },
    {
     "expr": "sum(binderhub_inprogress_launches)",
     "legendFormat": "launches"
    }
   ]
  },
  {
   "title": "User pods running, last hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-.*\", phase=\"Running\"}) by (phase)",
     "legendFormat": "GKE"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^jupyter-.*\", phase=\"Running\", kubernetes_namespace!=\"jhub-ns\"})",
     "legendFormat": "Gesis"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-.*\", phase=\"Running\"}) by (phase)",
     "legendFormat": "OVH"
    }
   ]
  },
  {
   "title": "Launch success %, last hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(increase(binderhub_launch_time_seconds_count{status=\"success\", kubernetes_namespace!=\"jhub-ns\"}[10m])) / sum(increase(binderhub_launch_time_seconds_count{status!=\"retry\", kubernetes_namespace!=\"jhub-ns\"}[10m])))",
     "legendFormat": "Launch success (${cluster})"
    },
    {}
   ]
  },
  {
   "title": "Launch time percentiles, last hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(binderhub_launch_time_seconds_bucket{status=\"success\"}[5m])) without (instance, repo, provider, retries)) > 0",
     "legendFormat": "10th-percential"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(binderhub_launch_time_seconds_bucket{status=\"success\"}[5m])) without (instance, repo, provider, retries)) > 0",
     "legendFormat": "25th-percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(binderhub_launch_time_seconds_bucket{status=\"success\"}[5m])) without (instance, repo, provider, retries)) > 0",
     "legendFormat": "50th-percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(binderhub_launch_time_seconds_bucket{status=\"success\"}[5m])) without (instance, repo, provider, retries)) > 0",
     "legendFormat": "75th-percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(binderhub_launch_time_seconds_bucket{status=\"success\"}[5m])) without (instance, repo, provider, retries)) > 0",
     "legendFormat": "90th-percentile"
    }
   ]
  }
 ]
}