{
 "title": "Pod Activity",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Most Popular Repositories (last hour)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(delta(binderhub_launch_count_total{status=\"success\", kubernetes_namespace!=\"jhub-ns\"}[1h])) by (repo))"
    }
   ]
  },
  {
   "title": "User pods running over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^jupyter-.*\", kubernetes_namespace!=\"jhub-ns\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Top 5 popular repositories (by number of launches in last hour)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(binderhub_launch_count_total{status=\"success\", repo!~\".*(jupyterlab-demo|ipython-in-depth|binder-examples).*\", kubernetes_namespace!=\"jhub-ns\"}[1h])) by (repo))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Successful builds in last hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(binderhub_build_count_total{status=\"success\", repo!~\".*(jupyterlab-demo|ipython-in-depth|binder-examples).*\"}[1h])) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "All build attempts in last hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(binderhub_build_count_total{repo!~\".*(jupyterlab-demo|ipython-in-depth|binder-examples).*\"}[1h])) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Build pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"build-.*\", kubernetes_namespace!=\"jhub-ns\"}) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(binderhub_inprogress_builds)",
     "legendFormat": "Build-watching requests"
    }
   ]
  },
  {
   "title": "Non-running pods by node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_status_phase{pod=~\"jupyter-.*\",phase!=\"Running\"}\n    * on (pod) group_left(node)\n    sum(kube_pod_info{pod=~\"jupyter-.*\"}) by (pod, node)\n) by (node, phase)",
     "legendFormat": "{{node}} | {{phase}}"
    }
   ]
  },
  {
   "title": "Pods running by regexp (jupyter-jupyterlab.*)",
   "type": "timeseries",
   "description": "Edit the regular expression in \"metrics\" to search for a different pod.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"jupyter-jupyterlab.*\"}) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"jupyter-jupyterlab.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-jupyterlab.*\",phase=\"Pending\"}) by (phase)",
     "legendFormat": "Pods in pending state"
    }
   ]
  },
  {
   "title": "Top 5 Pods CPU usage (2m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Launch Failing Repositories (10m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(binderhub_launch_count_total{status!=\"success\",status!=\"pod_quota\"}[10m])) by (status, repo) > 0",
     "legendFormat": "{{ repo }} ({{ status }})"
    },
    {
     "expr": "sum(increase(binderhub_launch_count_total{status=\"pod_quota\"}[10m])) > 0",
     "legendFormat": "all repos (pod_quota)"
    }
   ]
  },
  {
   "title": "Build Failing Repositories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(floor(increase(binderhub_build_count_total{status=\"failure\"}[$__interval]))) by (repo) > 0",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Pods with sustained CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "max(topk(10, container_cpu_usage_seconds_total{pod=~\"jupyter-.*\", container=\"notebook\"}) > 1800) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "count(1800 < container_cpu_usage_seconds_total{pod=~\"jupyter-.*\", container=\"notebook\"})",
     "legendFormat": "total cpu > 30m"
    }
   ]
  },
  {
   "title": "Percentiles of pod age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(.05, (time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60)",
     "legendFormat": "5%"
    },
    {
     "expr": "quantile(.25, (time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60)",
     "legendFormat": "25%"
    },
    {
     "expr": "quantile(.5, (time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60)",
     "legendFormat": "50%"
    },
    {
     "expr": "quantile(.75, (time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60)",
     "legendFormat": "75%"
    },
    {
     "expr": "quantile(.95, (time() - kube_pod_created{pod=~\"^jupyter.*\"}) / 60)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Launch success rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(binderhub_launch_count_total{status=\"success\"}[5m])) / sum(increase(binderhub_launch_count_total{status!=\"retry\"}[5m]))",
     "legendFormat": "Launch success"
    },
    {
     "expr": "sum(increase(binderhub_launch_count_total[5m]))",
     "legendFormat": "Launch attempts"
    },
    {
     "expr": "sum(increase(binderhub_launch_count_total{status=\"success\",retries!=\"0\",retries!=\"\"}[5m])) / sum(increase(binderhub_launch_count_total{status!=\"retry\"}[5m]))",
     "legendFormat": "Retry rate"
    }
   ]
  },
  {
   "title": "Percentiles of build pod age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(.95, (time() - kube_pod_created{pod=~\"^build-.*\"}) / 60)",
     "legendFormat": "95 percentile of build pod age"
    }
   ]
  }
 ]
}