{
 "title": "Components Resource Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "BinderHub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "JupyterHub CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"hub-.*\", container!=\"\"}[2m])) by (pod)",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "BinderHub CPU Usage (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"binder-.*\", container!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Proxy CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"proxy-.*\", container!=\"\"}[2m])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "JupyterHub Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"hub-.*\",container!=\"\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Binder Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"binder-.*\",container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Proxy Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"proxy-.*\", container!=\"\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "DinD builder Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".*-dind-.*\",container!=\"\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DinD builders CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*-dind-.*\",container!=\"\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Component resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "cluster" },
  {
   "title": "Prometheus Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*-prometheus-server-.*\",container!=\"\"}[2m]))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Prometheus Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".+-prometheus-server-.*\",container!=\"\"}) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus storage",
   "type": "timeseries",
   "description": "The amount of storage being used by prometheus\n\nadjust prometheus storage size and retention to avoid filling up",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes",
     "legendFormat": "prometheus storage"
    }
   ]
  },
  {
   "title": "Grafana CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".+-grafana-.*\",container!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Grafana Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".+-grafana-.*\",container!=\"\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Harbor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*-harbor-.*\",container!=\"\"}[2m])) by (container)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nginx Ingress CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"[[:alnum:]-]+-ingress[[:alnum:]-]+controller-.*\",container!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "nginx Ingress Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"[[:alnum:]-]+-ingress[[:alnum:]-]+controller-.*\",container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Harbor Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".*-harbor-.*\",container!=\"\"}) by (container)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "federation redirector CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"federation-redirect-.*\",container!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "federation redirector Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"federation-redirect-.*\",container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "user scheduler CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"user-scheduler-.*\",container!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "analytics publisher CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"analytics-publisher-.*\",container!=\"\"}[2m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "analytics publisher Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"analytics-publisher-.*\",container!=\"\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "user scheduler Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"user-scheduler-.*\",container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}