{
 "title": "Node Activity",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Placeholder pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"user-placeholder.*\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "User Pods per node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"jupyter-.*\"}) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "avg(count(kube_pod_info{pod=~\"jupyter-.*\"}) by (node))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Nodes in the user pool",
   "type": "graph",
   "description": "Number of nodes in the user pool.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info{node!~\".*-core-.*\"}) ",
     "legendFormat": "Nodes"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "Cordoned"
    }
   ]
  },
  {
   "title": "Build pods per node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"build-.*\"}) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"build-.*\"})",
     "legendFormat": "Total build pods"
    }
   ]
  },
  {
   "title": "Docker Image Pulls (5m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kubelet_runtime_operations_total{operation_type=\"pull_image\"}[5m]) )",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(kubelet_runtime_operations_total{operation_type=\"pull_image\"}[5m])",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "DiskAvailable on Nodes",
   "type": "timeseries",
   "description": "Total amount of disk space available on the node for each mountpoint. A reading of 0 would be \"out of disk space\". A sharp increase toward the top of the chart indicates that Kubernetes has cleaned up disk space.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=~\"/.*\",device=~\"/.*\"}",
     "legendFormat": "{{ node }} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "MemAvailable on Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Image pulling latency (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(kubelet_runtime_operations_duration_seconds_bucket{operation_type=\"pull_image\"}[10m]))",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Pod Start Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_pod_start_duration_seconds_sum[2m])",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Cordoned Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube_node_spec_unschedulable", "legendFormat": "{{ node }}" }
   ]
  },
  {
   "title": "Requested memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} and on (pod) (kube_pod_container_status_ready)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Launch success %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(binderhub_launch_time_seconds_count{status=\"success\"}[5m])) / sum(increase(binderhub_launch_time_seconds_count{status!=\"retry\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(binderhub_launch_time_seconds_count{status=\"success\",retries=\"0\"}[5m])) / sum(increase(binderhub_launch_time_seconds_count{status!=\"retry\"}[5m]))",
     "legendFormat": "Success (first try)"
    }
   ]
  },
  {
   "title": "CPU Load5 per core on each node",
   "type": "graph",
   "description": "CPU 5-minute load average per core on each node (nodes sustained above 1 are overloaded)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5 / on(node) group_left sum(kube_node_status_capacity{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Age (days)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg((time() - kube_node_created) / 60 / 60 / 24) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}