{
 "title": "Usage Dashboard",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Active users (over 30 days)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n  sum(\n    min_over_time(\n      kube_pod_labels{\n        label_app=\"jupyterhub\",\n        label_component=\"singleuser-server\",\n        label_hub_jupyter_org_username!~\"(service|perf|hubtraf)-\",\n      }[30d]\n    )\n  ) by (pod)\n)\n",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Active users (over 24 hours)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n  sum(\n    min_over_time(\n      kube_pod_labels{\n        label_app=\"jupyterhub\",\n        label_component=\"singleuser-server\",\n        label_hub_jupyter_org_username!~\"(service|perf|hubtraf)-\",\n      }[1d]\n    )\n  ) by (pod)\n)\n",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Current running users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{phase=\"Running\"}\n  * on(pod, namespace) kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\"}\n)\n",
     "legendFormat": "Users"
    }
   ]
  }
 ]
}