{
 "title": "Network Activity",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Response codes (binder)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests/min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{service=\"binder\"}[5m]) * 60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response codes (hub)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "requests/min" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(nginx_ingress_controller_requests{service=\"proxy-public\"}[5m]) * 60) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Response codes (Federation Redirector)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{service=\"federation-redirect\"}[5m]) * 60)  by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitHub requests remaining",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(binderhub_github_rate_limit_remaining) without (instance)",
     "legendFormat": "requests-remaining"
    }
   ]
  }
 ]
}