projectName: gesis-acceptance
analyticsPublisher:
  enabled: false
binderhub:
  config:
    BinderHub:
      hub_url: https://notebooks-test.gesis.org/binder/jupyter/
    KubernetesBuildExecutor:
      memory_limit: 3G
      memory_request: 1G
    LaunchQuota:
      total_quota: 30
  extraConfig:
    01-template-variables: >
      template_vars = {
        "gesis_notebooks_https": 'https://notebooks-test.gesis.org/',
        'production': False,
      }

      template_vars['gesis_notebooks_static'] =
      template_vars['gesis_notebooks_https'] + "static/"

      template_vars['gesis_web_frontend_framework'] =
      template_vars['gesis_notebooks_static'] + "gesis-web-frontend-framework/"

      template_vars['binder_static'] = template_vars['gesis_notebooks_https'] +
      "binder/static/"

      c.BinderHub.template_variables.update(template_vars)
  imageCleaner:
    # size is given in bytes, i.e. 1GB = 1e9
    imageGCThresholdHigh: 10e9
    imageGCThresholdLow: 5e9
    imageGCThresholdType: absolute
  ingress:
    hosts:
      - notebooks-test.gesis.org
  jupyterhub:
    ingress:
      hosts:
        - notebooks-test.gesis.org
cryptnono:
  enabled: true
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - disableDeletion: true
          editable: false
          folder: notebooks.gesis.org
          name: default
          options:
            path: /var/lib/grafana/dashboards/notebooks.gesis.org
          orgId: 1
          type: file
  grafana.ini:
    server:
      root_url: https://notebooks.gesis.org/grafana/
  ingress:
    hosts:
      - notebooks-test.gesis.org
  nodeSelector:
  resources:
    limits:
      cpu: "0.25"
      memory: 128Mi
    requests:
      cpu: "0"
      memory: 128Mi
prometheus:
  server:
    ingress:
      hosts:
        - notebooks-test.gesis.org
    persistentVolume:
      size: 1Gi
      storageClass: local-storage-prometheus
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    retention: 30d
static:
  ingress:
    hosts:
      - notebooks-test.gesis.org
url: https://notebooks-test.gesis.org/binder/
