projectName: hetzner-gesis

binderhub:
  config:
    BinderHub:
      hub_url: https://hub.gesis.mybinder.org
      badge_base_url: https://mybinder.org
      image_prefix: oci.2i2c.mybinder.org/mybinder-builds/i-
      sticky_builds: true
    KubernetesBuildExecutor:
      docker_host: /var/run/dind/docker.sock
      repo2docker_extra_args:
        # try to avoid timeout pushing to local registry
        # default is 60
        # this must have no spaces to be processed by repo2docker correctly
        - '--DockerEngine.extra_init_args={"timeout":1200}'

    LaunchQuota:
      total_quota: 180

  replicas: 2

  extraVolumes:
    - name: secrets
      secret:
        secretName: events-archiver-secrets
  extraVolumeMounts:
    - name: secrets
      mountPath: /secrets
      readOnly: true
  extraEnv:
    GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json

  dind:
    resources:
      requests:
        cpu: "4"
        memory: 12Gi
      limits:
        cpu: "8"
        memory: 16Gi

  ingress:
    hosts:
      - gesis.mybinder.org

  jupyterhub:
    # proxy:
    #   chp:
    #     resources:
    #       requests:
    #         cpu: "1"
    #       limits:
    #         cpu: "1"
    ingress:
      hosts:
        - hub.gesis.mybinder.org
      tls:
        - secretName: kubelego-tls-hub
          hosts:
            - hub.gesis.mybinder.org

  imageCleaner:
    # handled by buildkit pruner
    enabled: false

harbor:
  enabled: true
  expose:
    ingress:
      annotations:
      hosts:
        core: registry.gesis.mybinder.org
  persistence:
    imageChartStorage:
      s3:
        # https://github.com/goharbor/harbor-helm/blob/v1.18.1/values.yaml#L225
        region: does-not-matter
        bucket: mybinder-2i2c-gesis-registry
        regionendpoint: https://nbg1.your-objectstorage.com
        rootdirectory: harbor
  core:
    replicas: 2
  registry:
    replicas: 2

grafana:
  ingress:
    hosts:
      - grafana.gesis.mybinder.org
    tls:
      - hosts:
          - grafana.gesis.mybinder.org
        secretName: kubelego-tls-grafana
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://prometheus.gesis.mybinder.org
          access: direct
          isDefault: true
          editable: false
  # persistence:
  # storageClassName: csi-cinder-high-speed

prometheus:
  server:
    persistentVolume:
      size: 50Gi
    ingress:
      hosts:
        - prometheus.gesis.mybinder.org
      tls:
        - hosts:
            - prometheus.gesis.mybinder.org
          secretName: kubelego-tls-prometheus
  extraScrapeConfigs: |
    - job_name: 'harbor-exporter'
      static_configs:
        - targets:
            - hetzner-gesis-harbor-exporter:8001
    - job_name: 'harbor-registry'
      static_configs:
        - targets:
            - hetzner-gesis-harbor-registry:8001
    - job_name: 'harbor-jobservice'
      static_configs:
        - targets:
            - hetzner-gesis-harbor-jobservice:8001

ingress-nginx:
  controller:
    replicas: 1
    scope:
      enabled: true
    service:
      loadBalancerIP: 116.203.245.43

static:
  ingress:
    hosts:
      - static.gesis.mybinder.org
    tls:
      secretName: kubelego-tls-static
