binderhub:
  config:
    BinderHub:
      use_registry: false

  extraConfig:
    # Disable send events to StackDriver on Google Cloud
    01-eventlog:

  registry:
    username: "your-username"
    # This is unsafe! Only se for local development
    password: "your-password"

  ingress:
    hosts:
      - localhost

  jupyterhub:
    ingress:
      hosts:
        - jupyterhub.localhost

static:
  ingress:
    tls:
      enabled: false
    hosts:
      - static.localhost

analyticsPublisher:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

cryptnono:
  enabled: false

cluster-autoscaler:
  enabled: false