binderhub:
  config:
    BinderHub:
      # Use Kubernetes DNS
      hub_url: http://hub:8081
      use_registry: false

  extraConfig:
    # Disable send events to StackDriver on Google Cloud
    01-eventlog:

  registry:
    username: "your-username"
    # This is unsafe! Only se for local development
    password: "your-password"

  ingress:
    https:
      # This is unsafe! Only se for local development
      enabled: false
    hosts:
      - 127.0.0.1.nip.io

  jupyterhub:
    ingress:
      hosts:
        - jupyterhub.127.0.0.1.nip.io

static:
  ingress:
    tls:
      # This is unsafe! Only se for local development
      enabled: false
    hosts:
      - static.127.0.0.1.nip.io

analyticsPublisher:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

cryptnono:
  enabled: false

cluster-autoscaler:
  enabled: false
