binderhub:
  registry:
    username: "your-username"
    # This is unsafe! Only se for local development
    password: "your-password"

  ingress:
    hosts:
      - localhost

  jupyterhub:
    ingress:
      hosts:
        - localhost

static:
  ingress:
    hosts:
      - localhost
      - localhost

analyticsPublisher:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

cryptnono:
  enabled: false

cluster-autoscaler:
  enabled: false