apiVersion: v1
kind: Secret
metadata:
  name: analytics-publisher-secrets
  labels:
    app: analytics-publisher
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  service-account.json: {{ .Values.analyticsPublisher.serviceAccountKey | b64enc | quote }}
