{{- if .Values.static.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: static-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  static.conf: |
    server {
      listen 80;
      root /www/data;
      location / {
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: static-files
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- (.Files.Glob "files/static/*").AsConfig | nindent 2 }}
{{- end }}
