apiVersion: v2
description: A meta-chart for the binderhub deployment on mybinder.org
name: mybinder
version: "0.0.1-set.by.chartpress"
kubeVersion: ">= 1.15.0-0"
dependencies:
  # BinderHub
  # Source code:    https://github.com/jupyterhub/binderhub/tree/main/helm-chart
  # App changelog:  https://github.com/jupyterhub/binderhub/blob/main/CHANGES.md
  - name: binderhub
    version: "1.0.0-0.dev.git.3025.h276be90"
    repository: https://jupyterhub.github.io/helm-chart

  # Ingress-Nginx to route network traffic according to Ingress resources using
  # this controller from within k8s.
  # Source code:   https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
  # App changelog: https://github.com/kubernetes/ingress-nginx/blob/main/Changelog.md
  #
  # NOTE: chart v3.36.0 maps to v0.49.0 and has support for networking.k8s.io/v1
  #       chart v4.1.2 maps to v1.2.0 and has dropped support for networking.k8s.io/v1beta1
  - name: ingress-nginx
    version: "4.5.2"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

  # Prometheus for collection of metrics.
  # Source code:   https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  # App changelog: https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md
  #
  # NOTE: chart v11.0.2 maps to app v2.16.0   - 2020-07-10
  #       chart v11.16.9 maps to app v2.21.0  - 2020-12-06
  #       chart v12 requires Helm 3
  - name: prometheus
    version: "19.7.2"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  # Grafana for dashboarding of metrics.
  # Source code:   https://github.com/grafana/helm-charts/tree/main/charts/grafana
  # App changelog: https://github.com/grafana/grafana/blob/main/CHANGELOG.md
  #
  # NOTE: chart v3.10.1 maps to app v6.4.2   - 2019-11-22
  #       chart v5.0.26 maps to app v6.7.3   - 2020-12-06
  #       chart v5.1.2 maps to app v7.0.1
  #       chart v6 requires Helm 3
  #       chart v6.17.1 gives us Grafana v8.2.1
  - name: grafana
    version: "6.52.1"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

  # cryptnono, counters crypto mining
  # Source code: https://github.com/yuvipanda/cryptnono/
  - name: cryptnono
    version: "0.0.1-n025.h28f473f"
    repository: https://yuvipanda.github.io/cryptnono/
    condition: cryptnono.enabled
