apiVersion: v2
description: A meta-chart for the binderhub deployment on mybinder.org
name: mybinder
version: "2020.12.4-0.dev.git.6239.h41940d65"
kubeVersion: ">= 1.15.0-0"
dependencies:
  - name: jupyterhub
    version: 4.0.0
    repository: https://jupyterhub.github.io/helm-chart/

  - name: binderhub
    repository: file:///Users/yuvipanda/code/binderhub/helm-chart/binderhub/
    # repository: https://2i2c.org/binderhub-service/
    condition: binderhub.enabled
    version: "1.0.0-0.dev.git.4013.hd0c659e9"

  # https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
  - name: ingress-nginx
    version: "4.12.0"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

  # Prometheus for collection of metrics.
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  - name: prometheus
    version: "26.1.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  # Grafana for dashboarding of metrics.
  # https://github.com/grafana/helm-charts/tree/main/charts/grafana
  - name: grafana
    version: "8.8.2"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

  # cryptnono, counters crypto mining
  # https://github.com/cryptnono/cryptnono/
  - name: cryptnono
    version: "0.3.2-0.dev.git.156.hdab4ec8"
    repository: https://cryptnono.github.io/cryptnono/
    condition: cryptnono.enabled

  # cluster autoscaler, autoscales k8s nodes, required for EKS clusters that
  # don't have this feature out of the box
  - name: cluster-autoscaler
    version: 9.21.1
    repository: https://kubernetes.github.io/autoscaler
    condition: cluster-autoscaler.enabled

  # Registry helper, used to create container repositories before pushing and to
  # fetch dynamic registry credentials
  - name: binderhub-container-registry-helper
    version: 0.2.4
    repository: https://www.manicstreetpreacher.co.uk/binderhub-container-registry-helper/
    condition: binderhub-container-registry-helper.enabled

  - name: localpv-provisioner
    version: 4.2.0
    repository: https://openebs.github.io/dynamic-localpv-provisioner
    condition: localpv-provisioner.enabled
