apiVersion: v2
description: A meta-chart for the binderhub deployment on mybinder.org
name: mybinder
version: 0.0.1-set.by.chartpress
kubeVersion: ">= 1.15.0-0"
dependencies:
  # Ingress-Nginx to route network traffic according to Ingress resources using
  # this controller from within k8s.
  # Source code:   https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
  # App changelog: https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md
  #
  # NOTE: chart v2.13.0 maps to app v0.35.0  - 2020-09-01
  #       chart v3 upgrade require k8s 1.16
  #       chart v3.3.0 maps to app v0.35.0
  #       chart v3.12.0 requires Helm 3
  - name: ingress-nginx
    version: 2.13.0
    repository: https://kubernetes.github.io/ingress-nginx

  # Prometheus for collection of metrics.
  # Source code:   https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  # App changelog: https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md
  #
  # NOTE: chart v11.0.2 maps to app v2.16.0   - 2020-07-10
  #       chart v11.16.9 maps to app v2.21.0  - 2020-12-06
  #       chart v12 requires Helm 3
  - name: prometheus
    version: 11.16.9
    repository: https://prometheus-community.github.io/helm-charts

  # Grafana for dashboarding of metrics.
  # Source code:   https://github.com/grafana/helm-charts/tree/main/charts/grafana
  # App changelog: https://github.com/grafana/grafana/blob/master/CHANGELOG.md
  #
  # NOTE: chart v3.10.1 maps to app v6.4.2   - 2019-11-22
  #       chart v5.0.26 maps to app v6.7.3   - 2020-12-06
  #       chart v5.1.2 maps to app v7.0.1
  #       chart v6 requires Helm 3
  - name: grafana
    version: 5.0.26
    repository: https://grafana.github.io/helm-charts

  # BinderHub
  # Source code:    https://github.com/jupyterhub/binderhub/tree/master/helm-chart
  # App changelog:  https://github.com/jupyterhub/binderhub/blob/master/CHANGES.md
  - name: binderhub
    version: 0.2.0-n604.h9bc978a
    repository: https://jupyterhub.github.io/helm-chart
