apiVersion: v2
description: A meta-chart for the binderhub deployment on mybinder.org
name: mybinder
version: "0.0.1-set.by.chartpress"
kubeVersion: ">= 1.15.0-0"
dependencies:
  # BinderHub
  # Source code:    https://github.com/jupyterhub/binderhub/tree/main/helm-chart
  # App changelog:  https://github.com/jupyterhub/binderhub/blob/main/CHANGES.md
  - name: binderhub
    version: "1.0.0-0.dev.git.3899.hcff0042b"
    repository: https://jupyterhub.github.io/helm-chart
    condition: binderhubEnabled

  # Ingress-Nginx to route network traffic according to Ingress resources using
  # this controller from within k8s.
  # Source code:   https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
  # App changelog: https://github.com/kubernetes/ingress-nginx/blob/main/Changelog.md
  - name: ingress-nginx
    version: "4.14.3"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

  # Prometheus for collection of metrics.
  # Source code:   https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  # App changelog: https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md
  - name: prometheus
    version: "28.9.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  # Grafana for dashboarding of metrics.
  # Source code:   https://github.com/grafana/helm-charts/tree/main/charts/grafana
  # App changelog: https://github.com/grafana/grafana/blob/main/CHANGELOG.md
  - name: grafana
    version: "10.5.15"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

  # cryptnono, counters crypto mining
  # Source code: https://github.com/cryptnono/cryptnono/
  - name: cryptnono
    version: "0.3.2-0.dev.git.256.he86658e"
    repository: https://cryptnono.github.io/cryptnono/
    condition: cryptnono.enabled

  # cluster autoscaler, autoscales k8s nodes, required for EKS clusters that
  # don't have this feature out of the box
  - name: cluster-autoscaler
    version: 9.21.1
    repository: https://kubernetes.github.io/autoscaler
    condition: cluster-autoscaler.enabled

  # Registry helper, used to create container repositories before pushing and to
  # fetch dynamic registry credentials
  - name: binderhub-container-registry-helper
    version: 0.2.4
    repository: https://www.manicstreetpreacher.co.uk/binderhub-container-registry-helper/
    condition: binderhub-container-registry-helper.enabled

  - name: localpv-provisioner
    version: 4.2.0
    repository: https://openebs.github.io/dynamic-localpv-provisioner
    condition: localpv-provisioner.enabled

  - name: harbor
    version: 1.18.1
    repository: https://helm.goharbor.io
    condition: harbor.enabled

  # Watch pod logs, send alerts to Zulip
  - name: k8s-log-alerter-zulip
    version: 0.1.2
    repository: https://www.manicstreetpreacher.co.uk/k8s-log-alerter-zulip/
    condition: k8s-log-alerter-zulip.enabled
