dependencies:
 - name: nginx-ingress
   version: 0.20.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 9.1.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 3.10.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.4.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: cert-manager
   repository: https://charts.jetstack.io
   version: v0.10.0
 - name: binderhub
   version: 0.2.0-889380c
   repository: https://jupyterhub.github.io/helm-chart
