dependencies:
 - name: nginx-ingress
   version: 0.20.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 7.4.4
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 1.18.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: cert-manager
   repository: https://charts.jetstack.io
   version: v0.10.0
 - name: binderhub
   version: 0.2.0-b9ed7f5
   repository: https://jupyterhub.github.io/helm-chart
