dependencies:
 - name: nginx-ingress
   version: 0.20.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 9.1.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 3.10.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.4.2
   repository: https://kubernetes-charts.storage.googleapis.com
   tags:
     - kubelego
 - name: cert-manager
   version: v0.12.0-beta.1
   repository: https://charts.jetstack.io
   tags:
     - certmanager
 - name: binderhub
   version: 0.2.0-045.089702b
   repository: https://jupyterhub.github.io/helm-chart
