dependencies:
 - name: nginx-ingress
   version: 0.8.13
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 4.5.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 0.5.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.1.12
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: binderhub
   version: 0.1.0-fc29c17
   repository: https://jupyterhub.github.io/helm-chart
