name: Terraform static checks

on:
  pull_request:
    paths:
      - "terraform/**"
  push:
    paths:
      - "terraform/**"
  workflow_dispatch:

# We can't run CI tests on Terraform, so use as many static linters as possible

jobs:
  terraform-pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: pip install pre-commit

      # https://github.com/terraform-linters/setup-tflint
      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.47.0

      - name: Run terraform pre-commit
        run: pre-commit run --all --config .pre-commit-config-terraform.yaml
